require: rubocop-rspec
AllCops:
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
